version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ReelsTgAppRequestStore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alct2lsm4742"
s3_prefix = "ReelsTgAppRequestStore"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
